=== Kaleesastha/TestSnippets/FailOver.dtd
<!-- AdventNet Web NMS Back End Fail Over Configuration DTD -->
<!ELEMENT FAILOVER ( PRIMARY?, STANDBY?, SERVER_PARAMS? ) >

<!ELEMENT PRIMARY EMPTY >
<!ATTLIST PRIMARY HEART_BEAT_INTERVAL CDATA #REQUIRED >
<!ATTLIST PRIMARY FAIL_OVER_INTERVAL CDATA #IMPLIED >

<!ELEMENT STANDBY ( BACKUP, HEART_BEAT_INTERVAL*, SEND_EMAIL*, HOTSTANDBY_PROCESSES? ) >
<!ATTLIST STANDBY FAIL_OVER_INTERVAL CDATA #REQUIRED >
<!ATTLIST STANDBY RETRY_COUNT CDATA #REQUIRED >
<!ATTLIST STANDBY HEART_BEAT_INTERVAL CDATA #IMPLIED>
<!ATTLIST STANDBY RETRY_INTERVAL CDATA #IMPLIED>

<!ELEMENT BACKUP (INCLUDE?, EXCLUDE?) >
<!ATTLIST BACKUP ENABLED (TRUE | FALSE) "TRUE" >
<!ATTLIST BACKUP BACKUP_INTERVAL CDATA #REQUIRED >

<!ELEMENT INCLUDE (DIR*, FILE*)>
<!ELEMENT EXCLUDE (DIR*, FILE*)>

<!ELEMENT FILE EMPTY>
<!ATTLIST FILE name CDATA #REQUIRED >

<!ELEMENT DIR EMPTY>
<!ATTLIST DIR name CDATA #REQUIRED >

<!ELEMENT SEND_EMAIL EMPTY >
<!ATTLIST SEND_EMAIL SMTP_SERVER CDATA #REQUIRED >
<!ATTLIST SEND_EMAIL TO_ADDRESS CDATA #REQUIRED > <!-- for multiple To addresses "," is the separator -->
<!ATTLIST SEND_EMAIL FROM_ADDRESS CDATA #REQUIRED >
<!ATTLIST SEND_EMAIL SUBJECT CDATA #REQUIRED >
<!ATTLIST SEND_EMAIL BODY CDATA #REQUIRED >
<!ELEMENT HOTSTANDBY_PROCESSES ( PROCESS+ ) >
<!ELEMENT PROCESS EMPTY>
<!ATTLIST PROCESS NAME CDATA #REQUIRED>
<!ELEMENT SERVER_PARAMS (PARAM+) >
<!ELEMENT PARAM EMPTY>
<!ATTLIST PARAM NAME CDATA #REQUIRED>
<!ATTLIST PARAM VALUE CDATA #REQUIRED>

=== Kaleesastha/TestSnippets/Include-Exclude_Retry_interval_hot_standy_mail_server_configured.FailOver.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE FAILOVER SYSTEM "FailOver.dtd">
<FAILOVER>
	<PRIMARY HEART_BEAT_INTERVAL="60" />
	<STANDBY FAIL_OVER_INTERVAL="60" RETRY_COUNT="3" RETRY_INTERVAL="40">
			<BACKUP ENABLED="TRUE" BACKUP_INTERVAL="600" >
			<INCLUDE>
				<DIR name="/myDir1"/>
				<FILE name="/myDir1/myDir2/myFile21.txt"/> <!--When you need to INCLUDE the entire directory do not configure this tag-->
			</INCLUDE>
			<EXCLUDE>
				<DIR name="/myDir1/myDir2"/>
				<FILE name="/myDir1/myDir2/myFile21.txt"/> <!--When you need to EXCLUDE the entire directory do not configure this tag-->
			</EXCLUDE>
		</BACKUP>
		<SEND_EMAIL
		SMTP_SERVER="mail-server1"
		TO_ADDRESS="srikanth@india.adventnet.com"
		FROM_ADDRESS="webnms-admin@india.adventnet.com"
		SUBJECT="Web NMS Primary Server Failed"
		BODY="The Web NMS Back End Server is failed and taken over by the Hot Stand By Server"/>
	</STANDBY>
	<SERVER_PARAMS>
		<PARAM NAME="HOTSTANDBY_MONITOR" VALUE="com.adventnet.nms.example.FailOverTransmitter"/>
		<PARAM NAME="MONITOR_PORT" VALUE="2014"/>
	</SERVER_PARAMS> 
</FAILOVER>
